### ISSUE TITLE
How to make blender work on console

### ISSUE THREAD

**Issue by duygusar** [melights/cnn_desmoke#1]
I would like to run render_smoke.py, however I can not make Blender run on the console as demonstrated (without GUI) in your readme ./blender --python ./render_smoke.py  I have installed blender and it seems to work just fine, I have tried to add render_smoke.py as a new add on by importing a folder as an add-on but I still can not make ./blender work.  Also, what is the function of place_holder_img? Is it just a single image to initialize the add_background process or is it just a showcase to show blender works? or should I read in the files beforehand (right now it is done after add_background) and use them instead? I have never worked with Blender before, so I would appreciate if you can answer.

**Comment by melights** [comment]
Hi,
You should cd into the folder of your blender binary before executing the commands. If it doesn't work, you can enter the GUI mode and change to scripting layout and copy the code and execute it.
place_holder_img is just a random image used for setting up the texture.

**Comment by duygusar** [comment]
Oh okay, I thought there was a way to run it without the GUI. The GUI still pops up but runs the script, thanks!
